# Generated by Django 4.2.3 on 2023-07-18 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Benefits',
            new_name='benefits',
        ),
    ]
