# Generated by Django 4.2.3 on 2023-07-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_apply_email_remove_apply_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='is_being_considered',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='to_accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apply',
            name='to_refuse',
            field=models.BooleanField(default=False),
        ),
    ]
