# Generated by Django 4.2.3 on 2023-07-22 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_apply_cover_letter_alter_apply_candidate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='Cover_letter',
            new_name='cover_letter',
        ),
    ]
