# Generated by Django 4.2.3 on 2023-07-23 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_rename_cover_letter_apply_cover_letter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='cover_letter',
            new_name='message',
        ),
    ]
